### ISSUE TITLE
Login bug

### ISSUE THREAD

**Issue by Maagiij** [constantin-p/dat16j-exam-project#17]
![53391b4e-b233-11e6-9e72-c5e2bbed404c](https://cloud.githubusercontent.com/assets/22005076/20726910/c32d3fdc-b677-11e6-8677-754e860e4df2.png)

Login bug when writing too fast.

**Comment by constantin-p** [comment]
IntelliJ console bug.
Cosmetic bug, doesn't affect the functionality (the input is still being read).
